// Angular/task-manager/src/app/components/auth/signup/signup.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators, AbstractControl, ValidationErrors } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../services/auth.service';
import { User } from '../../../models/user';

@Component({
  selector: 'app-signup',
  imports: [ReactiveFormsModule, RouterModule],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css'
})
export class SignupComponent {

  router = inject(Router);
  auth = inject(AuthService);
  errorMessage = signal('');


  form = new FormGroup({
    username: new FormControl('', [Validators.minLength(3), Validators.required, this.noSpace]),
    email: new FormControl('', [Validators.email, Validators.required]),
    password: new FormControl('', [Validators.minLength(8), Validators.required]),
    confirmPassword: new FormControl('', [Validators.minLength(8), Validators.required])
  },
    {
      validators: this.matchPasswordValidator
    }
  );


  noSpace(control: AbstractControl): ValidationErrors | null {
    return control.value.includes(" ") ? { noSpace: true } : null
  }

  matchPasswordValidator(control: AbstractControl): ValidationErrors | null {
    const password = control.get('password')?.value;
    const confirmPassword = control.get('confirmPassword')?.value;

    return password === confirmPassword ? null : { passwordMismatch: true }
  }


  get username() {
    return this.form.get('username');
  }

  get email() {
    return this.form.get('email');
  }

  get password() {
    return this.form.get('password');
  }

  get confirmPassword() {
    return this.form.get('confirmPassword');
  }

  onSubmit(): void {
    if (this.form.valid) {
      const user: User = {
        name: this.form.value.username!,
        email: this.form.value.email!,
        password: this.form.value.password!
      };

      this.auth.login(user.email, user.password).subscribe((users) => {
        if (users.length > 0) {
          this.errorMessage.set('User already exists');
        } else {
          this.auth.register(user).subscribe(() => {
            this.errorMessage.set('');
            this.router.navigate(['/login']);
          });
        }
      });
    }
  }

}

<div class="auth-container">
  <div class="auth-card">
    <h2>Sign Up</h2>

    <form [formGroup]="form" (ngSubmit)="onSubmit()">
      <!-- Username -->
      <div class="form-group">
        <label for="username">Username</label>
        <input 
          type="text"
          id="username"
          formControlName="username"
          class="form-control"
          placeholder="Enter your username"
        >

        @if (username?.invalid && (username?.dirty || username?.touched)) {
          <div class="error-message">
            @if (username?.errors?.['required']) {
              <span>Username is required.</span>
            }
            @if (username?.errors?.['minlength']) {
              <span>Username must be at least 3 characters.</span>
            }
            @if (username?.errors?.['noSpace']) {
              <span>Username cannot contain spaces.</span>
            }
          </div>
        }
      </div>

      <!-- Email -->
      <div class="form-group">
        <label for="email">Email</label>
        <input 
          type="email"
          id="email"
          formControlName="email"
          class="form-control"
          placeholder="Enter your email"
        >

        @if (email?.invalid && (email?.dirty || email?.touched)) {
          <div class="error-message">
            @if (email?.errors?.['required']) {
              <span>Email is required.</span>
            }
            @if (email?.errors?.['email']) {
              <span>Enter a valid email address.</span>
            }
          </div>
        }
      </div>

      <!-- Password -->
      <div class="form-group">
        <label for="password">Password</label>
        <input 
          type="password"
          id="password"
          formControlName="password"
          class="form-control"
          placeholder="Create a password"
        >

        @if (password?.invalid && (password?.dirty || password?.touched)) {
          <div class="error-message">
            @if (password?.errors?.['required']) {
              <span>Password is required.</span>
            }
            @if (password?.errors?.['minlength']) {
              <span>Password must be at least 8 characters.</span>
            }
          </div>
        }
      </div>

      <!-- Confirm Password -->
      <div class="form-group">
        <label for="confirmPassword">Confirm Password</label>
        <input 
          type="password"
          id="confirmPassword"
          formControlName="confirmPassword"
          class="form-control"
          placeholder="Confirm your password"
        >

        @if ((confirmPassword?.dirty || confirmPassword?.touched)) {
          <div class="error-message">
            @if (confirmPassword?.errors?.['required']) {
              <span>Please confirm your password.</span>
            } @else if (form.hasError('passwordMismatch')) {
              <span>Passwords must match.</span>
            }
          </div>
        }
      </div>

      @if (errorMessage()) {
        <div class="error-message global-error">
          {{ errorMessage() }}
        </div>
      }

      <!-- Submit -->
      <button type="submit" [disabled]="form.invalid" class="btn-primary">
        Sign Up
      </button>

      <p class="auth-switch">
        Already have an account?
        <a routerLink="/login">Login</a>
      </p>

    </form>
  </div>
</div>

// React/D05/src/pages/Signup/Signup.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useContext } from "react";
import { AuthContext } from "../../context/AuthContext";
import { signupApi } from "../../api/auth";
import { toast } from "react-toastify";
import "../Login/Auth.css";

const Signup = () => {
  const [formData, setFormData] = useState({ name: "", email: "", password: "" });
  const [errors, setErrors] = useState({});
  const { setUser, loading, setLoading } = useContext(AuthContext);
  const navigate = useNavigate();

  const validate = () => {
    const newErrors = {};
    if (!formData.name.trim()) {
      newErrors.name = "Username is required";
    } else if (formData.name.length < 3) {
      newErrors.name = "Username must be at least 3 characters";
    }
    if (!formData.email) {
      newErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = "Email is invalid";
    }
    if (!formData.password) {
      newErrors.password = "Password is required";
    } else if (formData.password.length < 8) {
      newErrors.password = "Password must be at least 8 characters";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    if (errors[e.target.name]) {
      setErrors({ ...errors, [e.target.name]: "" });
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;
    
    try {
      setLoading(true);
      const newUser = await signupApi(formData);
      setUser(newUser);
      localStorage.setItem("user", JSON.stringify(newUser));
      toast.success("Account created successfully!");
      navigate("/home");
    } catch (err) {
      toast.error("Signup failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <h1>Join TechNews</h1>
        <p>Create an account to get started</p>
        <form onSubmit={handleSubmit} noValidate>
          <div className="form-group">
            <label>Username</label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              className={errors.name ? "invalid" : ""}
              placeholder="Enter your name"
            />
            {errors.name && <span className="error-text">{errors.name}</span>}
          </div>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className={errors.email ? "invalid" : ""}
              placeholder="Enter your email"
            />
            {errors.email && <span className="error-text">{errors.email}</span>}
          </div>
          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className={errors.password ? "invalid" : ""}
              placeholder="Create a password"
            />
            {errors.password && <span className="error-text">{errors.password}</span>}
          </div>
          <button type="submit" className="auth-button" disabled={loading}>
            {loading ? "Signing up..." : "Sign Up"}
          </button>
        </form>
        <p className="auth-footer">
          Already have an account? <Link to="/login">Login</Link>
        </p>
      </div>
    </div>
  );
};

export default Signup;
