// React/D05/src/pages/Login/Login.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useContext } from "react";
import { AuthContext } from "../../context/AuthContext";
import { loginApi } from "../../api/auth";
import { toast } from "react-toastify";
import "../Login/Auth.css";

const Login = () => {
  const [formData, setFormData] = useState({ email: "", password: "" });
  const [errors, setErrors] = useState({});
  const { setUser, loading, setLoading } = useContext(AuthContext);
  const navigate = useNavigate();

  const validate = () => {
    const newErrors = {};
    if (!formData.email) {
      newErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = "Email is invalid";
    }
    if (!formData.password) {
      newErrors.password = "Password is required";
    } else if (formData.password.length < 8) {
      newErrors.password = "Password must be at least 8 characters";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    if (errors[e.target.name]) {
      setErrors({ ...errors, [e.target.name]: "" });
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;

    try {
      setLoading(true);
      const foundUser = await loginApi(formData);
      if (foundUser) {
        setUser(foundUser);
        localStorage.setItem("user", JSON.stringify(foundUser));
        toast.success("Welcome back!");
        navigate("/home");
      } else {
        toast.error("Invalid email or password");
      }
    } catch (err) {
      toast.error("Server error. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <h1>Welcome Back</h1>
        <p>Login to your account to continue</p>
        <form onSubmit={handleSubmit} noValidate>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className={errors.email ? "invalid" : ""}
              placeholder="Enter your email"
            />
            {errors.email && <span className="error-text">{errors.email}</span>}
          </div>
          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className={errors.password ? "invalid" : ""}
              placeholder="Enter your password"
            />
            {errors.password && <span className="error-text">{errors.password}</span>}
          </div>
          <button type="submit" className="auth-button" disabled={loading}>
            {loading ? "Logging in..." : "Login"}
          </button>
        </form>
        <p className="auth-footer">
          Don't have an account? <Link to="/signup">Sign up</Link>
        </p>
      </div>
    </div>
  );
};

export default Login;

// Angular/task-manager/src/app/components/auth/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { users } from '../../../users';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-login',
  imports: [FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  email: string = '';
  password: string = '';
  invalidCredentials = signal('');

  router = inject(Router)
  auth = inject(AuthService)


  onSubmit(form: NgForm) {
    if (form.valid) {
      this.auth.login(form.value.email, form.value.password).subscribe((users) => {
        console.log(users);
        if (users.length > 0) {
          const user = users[0];
          localStorage.setItem('user', JSON.stringify(user.name));
          this.router.navigate(['/lists']);
        } else {

          this.invalidCredentials.set('Invalid email or password');
        }
      });
    }
  }

  onInputChange() {
    this.invalidCredentials.set('');
  }
}

<div class="auth-container">
  <div class="auth-card">
    <h2>Login</h2>
    <form #loginForm="ngForm" (ngSubmit)="onSubmit(loginForm)">
      <div class="form-group">
        <label for="username">email</label>
        <input 
          type="text" 
          id="email" 
          name="email" 
          [(ngModel)]="email"   
          (input)="onInputChange()"
          required 
          #emailRef="ngModel"
          class="form-control"
          placeholder="Enter your email"
          pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"
        >
        @if (emailRef.invalid && (emailRef.dirty || emailRef.touched)) {
          <div class="error-message">
            @if (emailRef.errors?.['required']) {
              <span>email is required.</span>
            }
            @if (emailRef.errors?.['pattern']) {
              <span>Enter a valid email address.</span>
            }
          </div>
        }
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input 
          type="password" 
          id="password" 
          name="password" 
          [(ngModel)]="password"
          (input)="onInputChange()"
          required 
          minlength="3"

          #password="ngModel"
          class="form-control"
          placeholder="Enter your password"
        >
        @if (password.invalid && (password.dirty || password.touched)) {
          <div class="error-message">
            @if (password.errors?.['required']) {
              <span>Password is required.</span>
            }
            @if (password.errors?.['minlength']) {
              <span>Password must be at least 6 characters.</span>
            }
          </div>
        }
      </div>

      @if (invalidCredentials()) {
        <div class="error-message global-error">
          <span>{{ invalidCredentials() }}</span>
        </div>
      }

      <button type="submit" [disabled]="loginForm.invalid" class="btn-primary">Login</button>
      
      <p class="auth-switch">
        Don't have an account? <a routerLink="/signup">Sign up</a>
      </p>
    </form>
  </div>
</div>
